### ISSUE TITLE
레포지토리 이름 변경 제안

### ISSUE THREAD

**Issue by ecsimsw** [sucosuco/sucosuco_spring-suco_talk#6]
앞에 sucosuco/~ 를 붙이면 더 잘보일 것 같다.

![image](https://user-images.githubusercontent.com/46060746/120357821-d0014700-c340-11eb-810b-ea7bfb923af9.png)

**Comment by DWL5** [comment]
좋은 제안 입니다. 저도 동의하는 바라 일단 처리했어용
